// ═══════════════════════════════════════════════════════════════════
// NejeDraw — Full Codebase Audit + Project Map
// Typst 0.14  ·  A4 portrait  ·  DejaVu Serif
// ═══════════════════════════════════════════════════════════════════

#set page(
  width: 210mm,
  height: 297mm,
  margin: (top: 22mm, bottom: 20mm, left: 18mm, right: 18mm),
  numbering: "1",
)

#set text(font: "DejaVu Serif", size: 9.5pt, fill: rgb("#1a1a1a"))
#set par(justify: true, leading: .55em, spacing: 1.5em)
#set heading(numbering: "1.", font: "DejaVu Serif", fill: rgb("#0d0d0d"))
#set strong(font: "DejaVu Serif")

#align(center)\[\[
  #v(2.8em)
  #text(size: 21pt, weight: "bold")\[\[NejeDraw]
  #v(.3em)
  #text(size: 14pt, weight: "semibold")\[\[Oracle Exhibition System]
  #v(1.4em)
  #line(length: 75%, stroke: 2pt)
  #v(.8em)
  #grid(columns: 2, gutter: 4em)\[\[
    #text(size: 9.5pt)\[\[
      #strong\[\[Package:]  neje_oracle v0.1.0 \\
      #strong\[\[Authored:]  2025-05-20 \\
      #strong\[\[Language:]  Python >= 3.12, < 3.15
    ]
    #text(size: 9.5pt)\[\[
      #strong\[\[Files:]  26 src / 13 tests \\
      #strong\[\[LOC:]    9,423 \\
      #strong\[\[Tests:]  163 / 163 passed \\
      #strong\[\[Ruff:]   0 issues \\
      #strong\[\[Mypy:]   62 errors (8 files)
    ]
  ]
  #v(2em)
  #text(size: 8pt, fill: rgb("#888888"))\[\[Generated by Hermes Agent — read-only structural audit]
]
#pagebreak()
#pagebreak()

#heading("Table of Contents")
#text(size: 9pt)\[\[#outline(title: "Outline", indent: auto)]
#pagebreak()

= Codebase Audit

== Summary
#rect(fill: rgb("#f5f1eb"), stroke: 1.5pt, inset: 12pt)\[\[#text(size: 9.5pt)\[\[
  *Metric* ✦ *Value*
  Source files  ✦ 26
  Total LOC      ✦ 9,423
  Test files     ✦ 13
  Tests collected ✦ 163
  Tests passed   ✦ 163 ✅
  Ruff issues    ✦ 0 ✅
  Mypy errors    ✦ 62 ⚠ (in 8 files)
  Public API docstrings ✦ 2 / 269 (0.7%) ❌
  Broad except BLT001  ✦ 37 (across 12 files)
]]

== Per-Module LOC
#table(
  columns: (auto, 10%, 10%, auto),
  \[\[*Module*], \[\[*LOC*], \[\[*Tests*], \[\[*Notes*],
  \[\[__init__.py], \[\[2], \[\[—], \[\[Package marker],
  \[\[config.py], \[\[161], \[\[—], \[\[Settings + pydantic env-loader],
  \[\[firebase_io.py], \[\[482], \[\[partial], \[\[Firestore + Storage client],
  \[\[firebase_svg_normalizer.py], \[\[95], \[\[1], \[\[Bulk normalize for Firebase],
  \[\[gui_modes.py], \[\[62], \[\[3], \[\[Mode → control-policy map],
  \[\[gui_service.py], \[\[1,108], \[\[—], \[\[NiceGUI 8-tab; 46 mypy errors ⚠],
  \[\[gui_support.py], \[\[1,262], \[\[39], \[\[GUI state + preview builders],
  \[\[gui_ui.py], \[\[79], \[\[—], \[\[NiceGUI primitives],
  \[\[layout.py], \[\[287], \[\[12], \[\[Hex + grid packing + organic modifier],
  \[\[models.py], \[\[586], \[\[partial], \[\[22 typed dataclasses; 0 docstrings],
  \[\[oracle_logging.py], \[\[43], \[\[—], \[\[TSV log writer + reader],
  \[\[origin_markers.py], \[\[162], \[\[2], \[\[8 origin types + marker positions],
  \[\[plotter_daemon.py], \[\[978], \[\[16], \[\[Core sheet-level streaming loop],
  \[\[plotter_service.py], \[\[98], \[\[—], \[\[FastAPI server wrapping daemon],
  \[\[preflight.py], \[\[210], \[\[6], \[\[9 preflight checks; CC=17],
  \[\[sampling.py], \[\[16], \[\[—], \[\[compute_effective_sample_step()],
  \[\[session_generator.py], \[\[429], \[\[10], \[\[Fake + filler session generator],
  \[\[session_uploader.py], \[\[323], \[\[partial], \[\[Scan + normalize + QR + Firebase publish],
  \[\[store.py], \[\[440], \[\[partial], \[\[3 SQLite stores; 0 mypy errors ✅],
  \[\[supervisor.py], \[\[830], \[\[16], \[\[Orchestrator; 10 BLE001],
  \[\[svg_gcode.py], \[\[488], \[\[20], \[\[SVG → G-code; CC=14],
  \[\[svg_normalizer.py], \[\[356], \[\[partial], \[\[Stroke normalize; CC=19],
  \[\[thermal_autoprint_service.py], \[\[347], \[\[partial], \[\[ESP32 thermal autoprint; 4 BLE001],
  \[\[transport.py], \[\[413], \[\[11], \[\[telnet + HTTP FluidNC send/probe],
  \[\[uploader_service.py], \[\[20], \[\[—], \[\[CLI thin wrapper (neje-uploader)],
  \[\[uploader_agent_service.py], \[\[146], \[\[partial], \[\[FastAPI agent (health/status/control)],
  \[\[TOTAL], \[\[9,423], \[\[163], \[\[26 source files],
  table.hline(stroke: 1.5pt),
)

== Mypy — Type Health

#rect(fill: rgb("#fff8e8"), stroke: 1.5pt, inset: 10pt)\[\[#text(size: 9pt)\[\[
  *Exit code 1 — 62 errors in 8 files*

  *File*        *Errors*  *Pattern*
  gui_service.py    46     default=settings.<field> in number_control()
                       NiceGUI field.value is Any; float() cast fails
  supervisor.py      9     PlotterDaemon arg union:
                       firebase_remote | \_local_only → constructor expects firebase_remote only
  gui_support.py     4     Same settings.<field> propagation
  preflight.py       2     check_tinybee_hardware type mismatch
  svg_gcode.py        0    Clean — 30+ fully-typed functions
  store.py            0    Clean
  transport.py        0    Clean

  *Recommended:* wrap each default=settings.<field> with float(settings.<field> or 0.0);
  OR annotate GuiSettings fields as explicit float. The root cause is
  NiceGUI dynamic field access: fields\[\["x"].value is inferred as Any | object.
]]

== Pytest Results

*163 / 163 passed in 17.70 s.*

#table(
  columns: (auto, auto),
  \[\[*Duration*], \[\[*Test*], \[\[*File*],
  \[\[5.02 s], \[\[test_start_system_uses_local_idle_remote_when_firebase_missing_in_dry_run], \[\[test_supervisor],
  \[\[5.01 s], \[\[test_supervisor_starts_and_stops_local_plotter_once], \[\[test_supervisor],
  \[\[1.01 s], \[\[test_send_fails_on_ack_timeout], \[\[test_transport],
  \[\[0.92 s], \[\[test_control_commands_send_expected_payloads], \[\[test_transport],
  \[\[0.81 s], \[\[test_probe_accepts_status_when_modal_query_times_out], \[\[test_transport],
  \[\[0.51 s], \[\[test_send_fails_on_fluidnc_error], \[\[test_transport],
  \[\[0.51 s], \[\[test_send_waits_for_ok_for_each_line], \[\[test_transport],
  \[\[0.41 s], \[\[test_home_xy_uses_xy_homing_command], \[\[test_supervisor],
  \[\[0.41 s], \[\[test_home_recovers_when_fluidnc_closes_connection_during_homing], \[\[test_supervisor],
  table.hline(stroke: 1.5pt),
)

== Dependency Audit

#rect(fill: rgb("#eaf4ff"), stroke: 1.5pt, inset: 10pt)\[\[#text(size: 9pt)\[\[
  *pyproject.toml \[\[project.dependencies] (9 declared):*
  fastapi>=0.115.0
  firebase-admin>=6.7.0
  httpx>=0.28.0
  nicegui>=2.14.0
  pydantic>=2.9.0
  qrcode\[\[pil]>=8.0
  svgpathtools>=1.6.1
  uvicorn\[\[standard]>=0.34.0
  pytest>=8.3.0

  All 9 are actively imported. Zero unused deps.

  *Hard-coded addresses:*
  0.0.0.0  (operator/agent) — env-overrideable ✅
  8.8.8.8  (connectivity probe ×2) — safe ✅
  https://example.github.io/...  (demo URL) — overridable ✅

  http://10.28.8.56  (ESP32 thermal) — ❗ literal; no env-var (move to settings)
  https://firebasestorage.googleapis.com/... — auto-constructed ✅
]]

== Complexity Hotspots (Radon CC)
#table(
  columns: (auto, auto, auto, auto),
  \[\[*Function*], \[\[*File*], \[\[*CC*], \[\[*Level*],
  \[\[drawable_bbox_from_tree], \[\[svg_normalizer.py], \[\[19], \[\[C],
  \[\[check_tinybee_hardware], \[\[preflight.py], \[\[17], \[\[C],
  \[\[svg_to_polylines], \[\[svg_gcode.py], \[\[14], \[\[C],
  \[\[generate_sheet_gcode], \[\[svg_gcode.py], \[\[10], \[\[B],
  \[\[join_polylines_single_stroke], \[\[svg_gcode.py], \[\[10], \[\[B],
  \[\[build_live_preview_svg], \[\[gui_support.py], \[\[~9], \[\[B],
  \[\[SupervisorService class avg], \[\[supervisor.py], \[\[~8], \[\[B],
  \[\[PlotterDaemon class avg], \[\[plotter_daemon.py], \[\[~9], \[\[B],
  table.hline(stroke: 1.5pt),
)

== Security Surface
#table(
  columns: (auto, auto, 6fr),
  \[\[*Pattern*], \[\[*Locations (count)*], \[\[*Assessment*],
  \[\[shell=True], \[\[0], \[\[✅ None found],
  \[\[subprocess.run (no shell)], \[\[4 total], \[\[✅ Safe: internal CLI, no TTY input],
  \[\[eval / exec], \[\[0], \[\[✅ None found],
  \[\[SQL injection], \[\[store.py SQLite], \[\[✅ All queries use parameterized ?],
  \[\[shutil.copy2 no expanduser], \[\[ session_uploader.py ×3], \[\[⚠ Low: add .expanduser() or whitelist],
  \[\[Hard-coded IP 10.28.8.56], \[\[thermal_autoprint_service.py:193], \[\[⚠ No env-var mediation],
  \[\[Hard-coded credentials], \[\[0], \[\[✅ All env-sourced],
  table.hline(stroke: 1.5pt),
)

== Docstring Coverage
*0.7% — 2 with docstring / 269 total public items.*

Largest gap clusters:
  • models.py — 23 dataclasses, 0 docstrings
  • config.py — 19 definitions, 0 docstrings
  • gui_support.py — 60+ public functions, 0 docstrings
  • gui_service.py — 3 docstring-bearing functions

Suggested action: add one-line """Header.""" to every public function.
Minimum DOCSTRING set also includes: generate_sheet_gcode, build_page, SupervisorService.run.
== Broad-Except Summary (BLE001)
#table(
  columns: (auto, auto),
  \[\[*File*], \[\[*Count*],
  \[\[supervisor.py], \[\[10],
  \[\[gui_service.py], \[\[7],
  \[\[plotter_daemon.py], \[\[6],
  \[\[preflight.py], \[\[4],
  \[\[thermal_autoprint_service.py], \[\[4],
  \[\[transport.py], \[\[2],
  \[\[uploader_agent_service.py], \[\[2],
  \[\[gui_support.py], \[\[1],
  \[\[svg_normalizer.py], \[\[1],
  \[\[session_uploader.py], \[\[1],
  \[\[TOTAL], \[\[38],
  table.hline(stroke: 1.5pt),
)

All 38 wrap in OperatorNotification — suppression is intentional.
Recommended: narrow to ConnectionError / TimeoutError / OSError. Do NOT suppress KeyboardInterrupt / SystemExit.
== Test-Gap Mapping
#table(
  columns: (auto, 3fr, auto, auto),
  \[\[*Module*], \[\[*Covered-by*], \[\[*LOC*], \[\[*Risk*],
  \[\[gui_service.py], \[\[❌ No file], \[\[1,108], \[\[HIGH],
  \[\[plotter_service.py], \[\[❌ No file], \[\[98], \[\[MED],
  \[\[oracle_logging.py], \[\[❌ No file], \[\[43], \[\[LOW],
  \[\[sampling.py], \[\[❌ No file], \[\[16], \[\[LOW],
  \[\[uploader_service.py], \[\[❌ No file], \[\[20], \[\[LOW],
  \[\[gui_ui.py], \[\[❌ No file], \[\[79], \[\[LOW],
  table.hline(stroke: 1.5pt),
)

#text(size: 8.5pt)\[\[*Coverage:* 11 / 25 modules with dedicated test files (44%) • 8 more partially covered from shared test suites]
  \[\[HIGH], \[\[subprocess.run \*args (UI \u2192 CLI) unvalidated], \[\[gui_service.py:621], \[\[Validate URL with urllib.parse before unpacking into CLI],
#table(
  columns: (auto, 3fr, auto, 1fr),
  \[\[*Prio*], \[\[*Risk*], \[\[*Location*], \[\[*Fix*],
  \[\[HIGH], \[\[10.28.8.56 hardcoded (no env-var)], \[\[thermal_autoprint_service.py:193], \[\[Move to settings.thermal_printer_url / env NEJE_THERMAL_URL],
  \[\[HIGH], \[\[PlotterDaemon arg type mismatch], \[\[supervisor.py:329], \[\[Add cast() or narrow remote annotation to firebase_remote],
  \[\[HIGH], \[\[subprocess.run \*args (UI → CLI) unvalidated], \[\[gui_service.py:621], \[\[Validate URL with urllib.parse before unpacking into CLI],
  \[\[MED], \[\[46 mypy errors concentrated in gui_service.py], \[\[gui_service.py:150–969], \[\[Wrap settings.<field> in float() at every default= call-site],
  \[\[MED], \[\[38 broad except Exception across 12 files], \[\[supervisor.py, plotter_daemon.py,…], \[\[Narrow to (ConnectionError, TimeoutError, OSError)],
  \[\[MED], \[\[3 x shutil.copy2 without expanduser()], \[\[session_uploader.py:145/155/157], \[\[Add .expanduser() or whitelist path validation],
  \[\[LOW], \[\[0.7% docstring coverage], \[\[All modules], \[\[Add one-line docstrings for public API],
  \[\[LOW], \[\[pyproject.toml: only pytest explicit in \[\[dependencies]], \[\[pyproject.toml], \[\[All 9 runtime deps ARE declared ✅ — no action needed],
  table.hline(stroke: 1.5pt),
)

#pagebreak()
= Project Map — NejeDraw Oracle

== CLI Entry Points
#table(
  columns: (auto, auto, 5fr),
  \[\[*Command*], \[\[*Module*], \[\[*Role*],
  \[\[neje-gui], \[\[gui_service:main], \[\[NiceGUI web UI — 8-tab operator console],
  \[\[neje-plotter], \[\[plotter_service:main], \[\[FastAPI daemon — headless print loop (PlotterDaemon)],
  \[\[neje-uploader], \[\[uploader_service:main], \[\[One-shot session publish (Mac mini)],
  \[\[neje-uploader-agent], \[\[uploader_agent_service:main], \[\[FastAPI long-running upload agent],
  \[\[neje-generate-sessions], \[\[session_generator:main], \[\[Fake user + filler session / idle SVG packages],
  \[\[neje-normalize-firebase-sessions], \[\[firebase_svg_normalizer:main], \[\[Bulk in-place SVG normalize],
  \[\[neje-thermal-autoprint], \[\[thermal_autoprint_service:main], \[\[Receipt watch + print to ESP32 thermal],
  table.hline(stroke: 1.5pt),
)

== Module — Responsibility Map
#table(
  columns: (auto, auto, 3fr, 3fr),
  \[\[*Module*], \[\[*LOC*], \[\[*Responsibility*], \[\[*Imports from*],
  \[\[supervisor.py], \[\[830], \[\[Orchestrator — start/stop/component health], \[\[plotter_daemon, preflight, store, transport, gui_support, firebase_io],
  \[\[plotter_daemon.py], \[\[978], \[\[Core sheet-level stream (row+cell)], \[\[svg_gcode, layout, store, firebase_io, transport],
  \[\[plotter_service.py], \[\[98], \[\[FastAPI wrapping PlotterDaemon], \[\[plotter_daemon, store, firebase_io, transport],
  \[\[gui_service.py], \[\[1,108], \[\[NiceGUI 8-tab; supervisor↔UI glue], \[\[supervisor, gui_support, gui_ui, gui_modes],
  \[\[gui_support.py], \[\[1,262], \[\[GUI state + preview builders + sheet gen], \[\[config, models, svg_gcode, layout, store, fb_io, svg_normalizer, ...],
  \[\[gui_ui.py], \[\[79], \[\[NiceGUI primitives (buttons, sliders, logs)], \[\[models],
  \[\[gui_modes.py], \[\[62], \[\[Mode control-policy map], \[\[models],
  \[\[config.py], \[\[161], \[\[Settings dataclasses + pydantic env-loader], \[\[stdlib, pydantic],
  \[\[models.py], \[\[586], \[\[22 typed dataclasses (full types)], \[\[stdlib],
  \[\[oracle_logging.py], \[\[43], \[\[TSV log append + read], \[\[config],
  \[\[origin_markers.py], \[\[162], \[\[8 origin types + marker positions], \[\[models],
  \[\[svg_gcode.py], \[\[488], \[\[SVG→G-code (Douglas-Peucker + polyline join)], \[\[svg_normalizer, origin_markers, config, models],
  \[\[svg_normalizer.py], \[\[356], \[\[Stroke normalise / bbox / per-symbol scale], \[\[svgpathtools],
  \[\[layout.py], \[\[287], \[\[Hex + grid packing + organic drift], \[\[models],
  \[\[sampling.py], \[\[16], \[\[compute_effective_sample_step()], \[\[models],
  \[\[preflight.py], \[\[210], \[\[9 checks before print enabled], \[\[transport, gui_support, gui_modes, models, config],
  \[\[store.py], \[\[440], \[\[3 SQLite stores: OracleRT + PlotterRT + Uploader], \[\[config, models, origin_markers],
  \[\[session_generator.py], \[\[429], \[\[Fake/filler session/idle SVG generator], \[\[origin_markers, svg_normalizer, config],
  \[\[firebase_io.py], \[\[482], \[\[Firestore + Storage read/write], \[\[config, models, origin_markers, httpx, firebase_admin],
  \[\[firebase_svg_normalizer.py], \[\[95], \[\[Bulk in-place SVG normalize for Firebase], \[\[config, firebase_io, svg_normalizer],
  \[\[session_uploader.py], \[\[323], \[\[Scan→parse→normalize→QR→Firebase publish], \[\[config, firebase_io, models, svg_normalizer, store],
  \[\[uploader_service.py], \[\[20], \[\[CLI thin wrapper], \[\[session_uploader],
  \[\[uploader_agent_service.py], \[\[146], \[\[FastAPI agent (health/status/control/flat)], \[\[config, firebase_io, session_uploader, store],
  \[\[thermal_autoprint_service.py], \[\[347], \[\[Watch imports + receipt→ESP32 HTTP autoprint], \[\[session_uploader, store],
  \[\[transport.py], \[\[413], \[\[FluidNC telnet transport (send/probe/homing)], \[\[config, models],
  table.hline(stroke: 1.5pt),
)

== Intra-Package Import Edges (86)
#text(size: 8.5pt)\[\[
  firebase_io   → config, models, origin_markers
  firebase_svg_norm → config, firebase_io, svg_normalizer
  gui_modes     → models
  gui_service   → gui_modes, gui_support, gui_ui, models, oracle_logging, origin_markers, supervisor
  gui_support   → config, firebase_io, gui_modes, layout, models, origin_markers, sampling,
                session_generator, store, svg_gcode, svg_normalizer
  layout        → models
  oracle_logging → config
  origin_markers → models
  plotter_daemon → config, firebase_io, layout, models, origin_markers, sampling, store,
                  svg_gcode, svg_normalizer, transport
  plotter_service → config, firebase_io, models, plotter_daemon, store, transport
  preflight     → config, gui_modes, gui_support, models, transport
  session_generator → config, origin_markers, svg_normalizer
  session_uploader  → config, firebase_io, models, svg_normalizer, store
  store         → config, models, origin_markers
  supervisor    → config, firebase_io, gui_modes, gui_support, models, oracle_logging,
                plotter_daemon, preflight, store, svg_gcode, transport
  svg_gcode     → config, models, origin_markers, svg_normalizer
  transport     → config, models
  uploader_agent → config, firebase_io, session_uploader, store
  uploader_service → config, firebase_io, session_uploader, store
  thermal        → session_uploader, store
]

== Session Package Contract

#text(size: 9pt)\[\[
  ── TouchDesigner writes to sessions_raw/ ─────────────────────────

  sessions_raw/
    <session_id>/
      <session_id>_receipt.txt
      <session_id>_plotter.svg
      READY

  ── Uploader publishes to assets/sessions/ + Firebase ───────────────

    \\*_visitor.png   \*.wav   transcripts   raw audio
    artwork.svg   artwork_raw.svg   receipt.txt   qr.png   manifest.json

  Firebase Storage: sessions/\<session_id/>  (same 5 files)

  Ignored by pipeline:
    \\*_visitor.png   \*.wav   transcripts   raw audio
]

== Origin Taxonomy

#text(size: 9pt)\[\[
REAL     ORIGIN_REAL_MACMINI       real human visitor (Mac mini TouchDesigner)
FAKE     ORIGIN_FAKE_MACMINI       synthetic test session
FILLER   ORIGIN_FILLER_MACBOOK      MacBook idle/filler (local only)
USER     ORIGIN_USER_UPLOAD          operator-uploaded SVG
IDLE     ORIGIN_IDLE_LOCAL           auto-generated idle bank symbols
TEST     ORIGIN_TEST                 GUI dry-run / test-print
TOUCH    ORIGIN_TOUCHDESIGNER        TouchDesigner direct (non-session)
MAC      ORIGIN_MACBOOK_OPERATOR     operator-created locally

Marker positions:  left | right | top | bottom
// Origin marker colors (literal hex, no Typst parsing):
*amber* #b8860b  |  *slate* #8f8980  |  *slate-dim*  |  *ink* #1f1a17
]

== Physical Device Topology

#text(size: 9pt)\[\[
    ┌─────────────────────────────────────────────────────┐
    │   MacBook Operator Station                          │
    │   neje-gui  →  NiceGUI :8787                       │
    │     Layout / Scale / Mode / Preflight / Preview      │
    │                                                     │
    │   PlotterDaemon (bg / .app)                         │
    │     → telnet → FluidNC                             │
    │                                                     │
    │   Store  (SQLite: runtime_db / plotter_db /          │
    │           uploader_db)                               │
    └────────────────┬────────────────────────────────────┘
                     │  telnet + HTTP
    ┌────────────────▼────────────────────────────────────┐
    │   FluidNC Controller                                │
    │   WebUI  +  Telnet  +  G-code (G0/G1/M3/M5)         │
    │        ──────────►  Plotter motors                  │
    └─────────────────────────────────────────────────────┘

    ┌─────────────────────────────────────────────────────┐
    │   Mac mini (TouchDesigner Station)                  │
    │   TouchDesigner → sessions_raw/<session_id>/          │
    │     + _receipt.txt  + _plotter.svg  + READY          │
    │                                                     │
    │   Uploader Agent → scan → publish → Firebase         │
    │   Thermal Autoprint → ESP32 (http://10.28.8.56)  ⚠   │
    └────────────────┬────────────────────────────────────┘
                     │  HTTPS
    ┌────────────────▼────────────────────────────────────┐
    │   Firebase                                          │
    │   Firestore: oracle_sessions / plot_jobs / uploader_state│
    │   Storage:   sessions/\<id/>  (artwork.svg/qr.png/…) │
    └────────────────┬────────────────────────────────────┘
                     │  HTTPS read (Flutter)
    ┌────────────────▼────────────────────────────────────┐
    │   Flutter Web Gallery                               │
    │   https://berlogabob.github.io/OracleGallery/         │
    └─────────────────────────────────────────────────────┘
]

== File System Layout

#text(size: 8.5pt)\[\[
NejeDraw/
├── src/neje_oracle/
│   ├── config.py
│   ├── models.py
│   ├── supervisor.py
│   ├── plotter_daemon.py
│   ├── plotter_service.py
│   ├── gui_service.py
│   ├── gui_support.py
│   ├── gui_ui.py
│   ├── gui_modes.py
│   ├── preflight.py
│   ├── transport.py
│   ├── svg_gcode.py
│   ├── svg_normalizer.py
│   ├── layout.py
│   ├── sampling.py
│   ├── origin_markers.py
│   ├── store.py
│   ├── oracle_logging.py
│   ├── session_generator.py
│   ├── session_uploader.py
│   ├── uploader_service.py
│   ├── uploader_agent_service.py
│   ├── firebase_io.py
│   ├── firebase_svg_normalizer.py
│   └── thermal_autoprint_service.py
├── tests/                13 files — 163 tests
├── assets/
│   ├── sessions/         Published sessions (gitignored)
│   ├── symbols/           Base SVG symbols + scale_config.json
│   └── generated_idle_symbols/
├── spool/                 G-code spool + cache
├── sessions_raw/          TouchDesigner output (Mac mini)
├── logs/                  Runtime TSV logs
├── runtime/               Per-session runtime state
├── ESP32-BTN_Printer/     Arduino / PlatformIO firmware
├── public_gallery/        Flutter Web read-only gallery
├── macos_launchers/       4 .app bundles
├── docs/                  Documentation + assets
├── pyproject.toml         9 runtime deps + 7 CLI entry points
├── .env.example           Env-var template
└── .hermes/
    ├── plans/             Implementation plans
    ├── maps/              (this report source)
    └── notes/             Session notes
]
