name: public_gallery
description: "Oracle public read-only gallery."
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  flutter_svg: ^2.0.10+1
  go_router: ^15.1.2
  google_fonts: ^6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - ../assets/symbols/20260416_213514_plotter.svg
    - ../assets/symbols/20260420_195415_plotter.svg
    - ../assets/symbols/20260421_195713_plotter.svg
    - ../assets/symbols/20260421_223735_plotter.svg
    - ../assets/symbols/test_the_kind_soul_220047_plotter.svg
    - ../assets/symbols/test_the_pitiful_story_215312_plotter.svg
    - ../assets/symbols/test_the_shriek_220002_plotter.svg
    - ../assets/symbols/test_the_thorns_215209_plotter.svg
